# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import items_pb2 as items__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in items_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ItemServiceStub(object):
    """The gRPC Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItemById = channel.unary_unary(
                '/dsa.items.ItemService/GetItemById',
                request_serializer=items__pb2.ItemIdRequest.SerializeToString,
                response_deserializer=items__pb2.Item.FromString,
                _registered_method=True)
        self.ListItems = channel.unary_stream(
                '/dsa.items.ItemService/ListItems',
                request_serializer=items__pb2.ListItemsRequest.SerializeToString,
                response_deserializer=items__pb2.Item.FromString,
                _registered_method=True)
        self.AddItems = channel.stream_unary(
                '/dsa.items.ItemService/AddItems',
                request_serializer=items__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=items__pb2.AddItemsResult.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/dsa.items.ItemService/UpdateItem',
                request_serializer=items__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=items__pb2.Item.FromString,
                _registered_method=True)
        self.DeleteItem = channel.unary_unary(
                '/dsa.items.ItemService/DeleteItem',
                request_serializer=items__pb2.ItemIdRequest.SerializeToString,
                response_deserializer=items__pb2.DeleteItemResponse.FromString,
                _registered_method=True)
        self.ChatAboutItems = channel.stream_stream(
                '/dsa.items.ItemService/ChatAboutItems',
                request_serializer=items__pb2.ChatMessage.SerializeToString,
                response_deserializer=items__pb2.ChatMessage.FromString,
                _registered_method=True)


class ItemServiceServicer(object):
    """The gRPC Service Definition
    """

    def GetItemById(self, request, context):
        """Unary: 1 request -> 1 response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListItems(self, request, context):
        """Server Streaming: 1 request -> many responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItems(self, request_iterator, context):
        """Client Streaming: many requests -> 1 response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Update an existing item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Delete an item
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatAboutItems(self, request_iterator, context):
        """Bidirectional Streaming: many requests <-> many responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItemById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemById,
                    request_deserializer=items__pb2.ItemIdRequest.FromString,
                    response_serializer=items__pb2.Item.SerializeToString,
            ),
            'ListItems': grpc.unary_stream_rpc_method_handler(
                    servicer.ListItems,
                    request_deserializer=items__pb2.ListItemsRequest.FromString,
                    response_serializer=items__pb2.Item.SerializeToString,
            ),
            'AddItems': grpc.stream_unary_rpc_method_handler(
                    servicer.AddItems,
                    request_deserializer=items__pb2.CreateItemRequest.FromString,
                    response_serializer=items__pb2.AddItemsResult.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=items__pb2.UpdateItemRequest.FromString,
                    response_serializer=items__pb2.Item.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=items__pb2.ItemIdRequest.FromString,
                    response_serializer=items__pb2.DeleteItemResponse.SerializeToString,
            ),
            'ChatAboutItems': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatAboutItems,
                    request_deserializer=items__pb2.ChatMessage.FromString,
                    response_serializer=items__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dsa.items.ItemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dsa.items.ItemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ItemService(object):
    """The gRPC Service Definition
    """

    @staticmethod
    def GetItemById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dsa.items.ItemService/GetItemById',
            items__pb2.ItemIdRequest.SerializeToString,
            items__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dsa.items.ItemService/ListItems',
            items__pb2.ListItemsRequest.SerializeToString,
            items__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItems(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dsa.items.ItemService/AddItems',
            items__pb2.CreateItemRequest.SerializeToString,
            items__pb2.AddItemsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dsa.items.ItemService/UpdateItem',
            items__pb2.UpdateItemRequest.SerializeToString,
            items__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dsa.items.ItemService/DeleteItem',
            items__pb2.ItemIdRequest.SerializeToString,
            items__pb2.DeleteItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatAboutItems(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dsa.items.ItemService/ChatAboutItems',
            items__pb2.ChatMessage.SerializeToString,
            items__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
