global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "rest-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rest-service:5000"]

  - job_name: "grpc-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["grpc-service:9103"]